### ISSUE TITLE
User can search for a character

### ISSUE THREAD

**Issue by patriciamanalang** [patriciamanalang/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can search for a character

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 10 11 29 AM](https://user-images.githubusercontent.com/109925604/201734999-ab1dc450-e3c3-4c62-82a7-e8eb54ff529f.png)
![Screen Shot 2022-11-14 at 10 12 00 AM](https://user-images.githubusercontent.com/109925604/201735011-0adb5e77-11a7-45b8-9b26-aa2ed30136cc.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a `div[data-view="home-view"] to the HTML.
- [x]  Add an input element of type search to search for an alumni to the `div[data-view="home-view"].
- [x]  Make sure to replicate the page wireframe from Figma.
- [x]  Ensure the page looks nice on both mobile-sized and desktop-sized screens.
- [x]  Listen for `'input'` events on the `search-box` input to update the page and show the character being search for.
- [x]  Make sure that click targets are either `<a>` or `<button>` elements.
- [x]  Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x]  Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x]  Remove all console logs.
  - [x]  Remove all commented out code.
  - [x]  Remove all CSS properties that have no effect.
  - [x]  Check all code for proper formatting and indentation.
  - [x]  Confirm that there are no errors in the console while using the application.
  - [x]  Confirm that all previous functionality still works without errors.
  - [x]  Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x]  Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
