### ISSUE TITLE
User can view information regarding the searched character

### ISSUE THREAD

**Issue by patriciamanalang** [patriciamanalang/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view information regarding the searched character

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 10 14 57 AM](https://user-images.githubusercontent.com/109925604/201735601-0031339a-a98a-4576-aae7-9eb867a2cefd.png)
![Screen Shot 2022-11-14 at 10 15 13 AM](https://user-images.githubusercontent.com/109925604/201735612-21c6297c-4ee9-4f60-a6dc-e200d0477ba6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a sibling `div[data-view="character-info"]` to the HTML.
- [x] Add some dummy information regarding a character in the HTML and style them to match the wireframe.
- [x] Define a function that will allow the user to view the character information when the user clicks on the character image.
- [x] Check that the character info page looks good on both mobile and desktop screens.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
