### ISSUE TITLE
User can create a "favorite characters" list

### ISSUE THREAD

**Issue by patriciamanalang** [patriciamanalang/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create a "favorite characters" list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 10 23 22 AM](https://user-images.githubusercontent.com/109925604/201736994-cf8ba623-9848-4da5-9dac-f32294be8a05.png)
![Screen Shot 2022-11-14 at 10 21 54 AM](https://user-images.githubusercontent.com/109925604/201736707-9250cc0c-da13-4c7d-9428-b12640afef78.png)
![Screen Shot 2022-11-14 at 10 18 24 AM](https://user-images.githubusercontent.com/109925604/201736293-827c5936-854a-4c9f-b572-854ae353e172.png)
![Screen Shot 2022-11-14 at 10 18 40 AM](https://user-images.githubusercontent.com/109925604/201736307-9914b421-9fec-4252-a3d6-4224efa3a26c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ...Add a sibling `div[data-view="favorites"]` to the HTML.
- [x] ...Add an empty unordered list to the `div[data-view="favorites"]` element in the HTML.
- [x] ...Add some dummy favorite characters list to the unordered list in the HTML and style them to match the wireframe.
- [x] ...Check that the favorite list looks good on both mobile and desktop screens.
- [x] ...Define a function that adds a character object to the favorites list page when the user clicks the heart icon.
- [x] Use a loop to create a DOM tree for each favorite character in the data model and append it to the page when the `'DOMContentLoaded'` event is fired.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
