### ISSUE TITLE
User can delete/remove characters from their "favorite characters" list

### ISSUE THREAD

**Issue by patriciamanalang** [patriciamanalang/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can delete/remove characters from their "favorite characters" list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-11-14 at 10 23 22 AM](https://user-images.githubusercontent.com/109925604/201736994-cf8ba623-9848-4da5-9dac-f32294be8a05.png)
![Screen Shot 2022-11-14 at 10 21 54 AM](https://user-images.githubusercontent.com/109925604/201736707-9250cc0c-da13-4c7d-9428-b12640afef78.png)
![Screen Shot 2022-11-14 at 10 25 32 AM](https://user-images.githubusercontent.com/109925604/201737426-2d9df6fb-5597-4968-8982-77ec5e80daf7.png)
![Screen Shot 2022-11-14 at 10 25 47 AM](https://user-images.githubusercontent.com/109925604/201737449-d052112a-5786-4751-9dfa-55efc1e3debf.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a click target for deleting a 'favorited' character on the trash can icon
- [x] Show a confirmation modal when the user clicks trash can icon click target
- [x] Hide the modal if the user clicks Cancel.
- [x] Remove the character from the data model and the favorites list DOM tree from the page if the user clicks Delete.
- [x] Show the favorites list if the user clicks Delete.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
